name: ampseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - alsa-lib=1.2.3
  - binutils_impl_linux-64=2.35.1
  - binutils_linux-64=2.35
  - bioconductor-biobase=2.46.0
  - bioconductor-biocgenerics=0.32.0
  - bioconductor-biocparallel=1.20.0
  - bioconductor-biostrings=2.54.0
  - bioconductor-dada2=1.14.0
  - bioconductor-delayedarray=0.12.0
  - bioconductor-genomeinfodb=1.22.0
  - bioconductor-genomeinfodbdata=1.2.2
  - bioconductor-genomicalignments=1.22.0
  - bioconductor-genomicranges=1.38.0
  - bioconductor-iranges=2.20.0
  - bioconductor-limma=3.42.0
  - bioconductor-rhtslib=1.18.0
  - bioconductor-rsamtools=2.2.0
  - bioconductor-s4vectors=0.24.0
  - bioconductor-shortread=1.44.0
  - bioconductor-summarizedexperiment=1.16.0
  - bioconductor-xvector=0.26.0
  - bioconductor-zlibbioc=1.32.0
  - biopython=1.76
  - brotlipy=0.7.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - ca-certificates=2021.5.30
  - cairo=1.16.0
  - certifi=2021.5.30
  - cffi=1.14.5
  - chardet=4.0.0
  - click=8.0.1
  - colorama=0.4.4
  - coloredlogs=15.0.1
  - colormath=3.0.0
  - commonmark=0.9.1
  - cryptography=3.4.7
  - curl=7.68.0
  - cutadapt=3.4
  - cycler=0.10.0
  - decorator=4.4.2
  - dnaio=0.5.1
  - fastqc=0.11.9
  - font-ttf-dejavu-sans-mono=2.37
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fribidi=1.0.10
  - future=0.18.2
  - gcc_impl_linux-64=7.5.0
  - gcc_linux-64=7.5.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=7.5.0
  - gfortran_linux-64=7.5.0
  - giflib=5.2.1
  - glib=2.68.3
  - glib-tools=2.68.3
  - graphite2=1.3.13
  - gsl=2.5
  - gxx_impl_linux-64=7.5.0
  - gxx_linux-64=7.5.0
  - harfbuzz=2.4.0
  - humanfriendly=9.2
  - icu=64.2
  - idna=2.10
  - importlib-metadata=4.5.0
  - isa-l=2.30.0
  - jbig=2.1
  - jinja2=3.0.1
  - jpeg=9d
  - kernel-headers_linux-64=2.6.32
  - kiwisolver=1.3.1
  - krb5=1.16.4
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.68.0
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-devel_linux-64=7.5.0
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.68.3
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libssh2=1.9.0
  - libstdcxx-devel_linux-64=7.5.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - lzstring=1.0.4
  - make=4.3
  - markdown=3.3.4
  - markupsafe=2.0.1
  - matplotlib-base=3.4.2
  - multiqc=1.10.1
  - muscle=3.8.1551
  - ncurses=6.2
  - networkx=2.5.1
  - numpy=1.20.3
  - olefile=0.46
  - openjdk=11.0.8
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - pandas=1.3.0
  - pango=1.42.4
  - pcre=8.45
  - perl=5.32.1
  - pigz=2.6
  - pillow=8.2.0
  - pip=21.1.2
  - pixman=0.38.0
  - pthread-stubs=0.4
  - pycparser=2.20
  - pygments=2.9.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.7.10
  - python-dateutil=2.8.1
  - python-isal=0.10.0
  - python_abi=3.7
  - pytz=2021.1
  - pyyaml=5.4.1
  - r-ade4=1.7_16
  - r-argparse=2.0.1
  - r-assertthat=0.2.1
  - r-base=3.6.1
  - r-bh=1.75.0_0
  - r-bitops=1.0_7
  - r-cli=2.5.0
  - r-codetools=0.2_18
  - r-colorspace=2.0_1
  - r-crayon=1.4.1
  - r-data.table=1.14.0
  - r-digest=0.6.27
  - r-domc=1.3.7
  - r-ellipsis=0.3.2
  - r-fansi=0.4.2
  - r-farver=2.1.0
  - r-findpython=1.0.7
  - r-foreach=1.5.1
  - r-formatr=1.9
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-ggplot2=3.2.1
  - r-glue=1.4.2
  - r-gtable=0.3.0
  - r-hms=1.1.0
  - r-hwriter=1.3.2
  - r-iterators=1.0.13
  - r-jpeg=0.1_8.1
  - r-jsonlite=1.7.2
  - r-labeling=0.4.2
  - r-lambda.r=1.2.4
  - r-lattice=0.20_44
  - r-latticeextra=0.6_29
  - r-lazyeval=0.2.2
  - r-lifecycle=1.0.0
  - r-magrittr=2.0.1
  - r-mass=7.3_54
  - r-matrix=1.3_2
  - r-matrixstats=0.58.0
  - r-mgcv=1.8_35
  - r-munsell=0.5.0
  - r-nlme=3.1_150
  - r-pillar=1.6.1
  - r-pixmap=0.4_12
  - r-pkgconfig=2.0.3
  - r-plyr=1.8.6
  - r-png=0.1_7
  - r-prettyunits=1.1.1
  - r-progress=1.2.2
  - r-r6=2.5.0
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.6
  - r-rcppparallel=5.1.4
  - r-rcurl=1.98_1.2
  - r-reshape2=1.4.4
  - r-rlang=0.4.11
  - r-scales=1.1.1
  - r-segmented=1.3_4
  - r-seqinr=4.2_5
  - r-snow=0.4_3
  - r-sp=1.4_5
  - r-stringi=1.4.6
  - r-stringr=1.4.0
  - r-tibble=3.1.2
  - r-utf8=1.2.1
  - r-vctrs=0.3.8
  - r-viridislite=0.4.0
  - r-withr=2.4.2
  - readline=8.1
  - requests=2.25.1
  - rich=10.3.0
  - sed=4.8
  - setuptools=49.6.0
  - simplejson=3.17.2
  - six=1.16.0
  - spectra=0.0.11
  - sqlite=3.35.5
  - sysroot_linux-64=2.12
  - tk=8.6.10
  - tktable=2.10
  - tornado=6.1
  - trim-galore=0.6.6
  - typing_extensions=3.10.0.0
  - urllib3=1.26.5
  - wheel=0.36.2
  - xopen=1.1.0
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.5.0


